# Generated by Django 2.2.5 on 2020-05-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0003_auto_20200504_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=25, max_length=200),
            preserve_default=False,
        ),
    ]
