# Generated by Django 2.2.5 on 2020-05-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0004_post_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='summary_text',
            new_name='additional_information',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body_text',
            new_name='description',
        ),
    ]
